web:
 image: wordpress
 links:
  - mysql
 environment:
  - WORDPRESS_DB_PASSWORD=password
 ports:
  - "127.0.0.3:8080:80"
 volumes:
  - "./wordpress:/var/www/html"
  - "./plugins:/var/www/html/wp-content/plugins"

mysql:
 image: mysql:5.7
 environment:
  - MYSQL_ROOT_PASSWORD=password
  - MYSQL_DATABASE=my-wpdb


